### ISSUE TITLE
auditable-build panics on Beta

### ISSUE THREAD

**Issue by Monadic-Cat** [Shnatsel/rust-audit#26] opened 2020-10-04 19:32 UTC
I have a crate, [mbot](https://github.com/Monadic-Cat/mbot) for which `auditable-build` successfully runs and this all works for on Stable, but for which `auditable-build` panics when building on Beta.
Some relevant command output:
```
jmn@neogreen:~/Projects/mprojects/mbot$ RUST_BACKTRACE=1 cargo +beta run --release --features auditable-data
   Compiling mbot v0.1.0 (/home/jmn/Projects/mprojects/mbot)
error: failed to run custom build command for `mbot v0.1.0 (/home/jmn/Projects/mprojects/mbot)`

Caused by:
  process didn't exit successfully: `/home/jmn/Projects/mprojects/mbot/target/release/build/mbot-35641d5a1f06aff7/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=data/maddie.json

  --- stderr
  thread 'main' panicked at 'no entry found for key', cargo/registry/src/github.com-1ecc6299db9ec823/auditable-serde-0.1.0/src/lib.rs:307:51
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9f0e6fa94be6f97c736e51811d7b58904edfa8cb/library/std/src/panicking.rs:475
     1: core::panicking::panic_fmt
               at /rustc/9f0e6fa94be6f97c736e51811d7b58904edfa8cb/library/core/src/panicking.rs:85
     2: core::option::expect_failed
               at /rustc/9f0e6fa94be6f97c736e51811d7b58904edfa8cb/library/core/src/option.rs:1213
     3: core::option::Option<T>::expect
     4: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
     5: <auditable_serde::VersionInfo as core::convert::TryFrom<&cargo_metadata::Metadata>>::try_from
     6: auditable_build::collect_dependency_list
     7: build_script_build::main
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Monadic-Cat** [comment] 2020-10-04 19:53
Upon regenerating the `Cargo.lock` in `mbot`, this issue vanishes. Somehow or other, my `Cargo.lock` was malformed. Nemo157 on Discord has guessed that this is related to https://github.com/rust-lang/cargo/pull/8522.

**Comment by Shnatsel** [comment] 2020-10-05 17:46
This is caused by an upstream bug: https://github.com/rust-lang/cargo/issues/8756

I'll keep this open until the upstream issue is resolved.

**Comment by Shnatsel** [comment] 2022-02-23 04:48
The upstream bug is fixed, so closing this issue.

**Closed by Shnatsel** 2022-02-23 04:48 UTC
Labels: bug, third party
